'use server'

import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'
import { createStockPurchase } from './supplier'

export async function getPurchaseOrders() {
  const supabase = await createClient()
  
  // Ambil PO berserta data nama supplier
  const { data, error } = await supabase
    .from('purchase_orders')
    .select(`
       *,
       suppliers (
         name, contact, address
       )
    `)
    .order('created_at', { ascending: false })
    
  if (error) {
    console.error("Error fetching getPurchaseOrders:", error)
    return []
  }
  return data
}

export async function getPurchaseOrderItems(poId: string) {
  const supabase = await createClient()
  
  const { data, error } = await supabase
    .from('purchase_order_items')
    .select(`
      *,
      products (name)
    `)
    .eq('po_id', poId)
    
  if (error) {
    console.error("Error fetching getPurchaseOrderItems:", error)
    return []
  }
  return data
}

export async function createPurchaseOrder(data: {
  supplier_id: string
  notes?: string
  items: Array<{ product_id: string; qty: number; cost_price: number }>
}) {
  const supabase = await createClient()

  // Generate simple PO format, e.g. PO-YYYYMMDD-Random(4)
  const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '')
  const randomStr = Math.floor(1000 + Math.random() * 9000)
  const poNumber = `PO-${dateStr}-${randomStr}`

  // 1. Buat header PO
  const { data: po, error: poErr } = await supabase
    .from('purchase_orders')
    .insert({
      po_number: poNumber,
      supplier_id: data.supplier_id,
      notes: data.notes || '',
      status: 'PENDING'
    })
    .select()
    .single()

  if (poErr) throw new Error(poErr.message)

  // 2. Buat item details PO
  const itemsToInsert = data.items.map(item => ({
    po_id: po.id,
    product_id: item.product_id,
    qty: item.qty,
    cost_price: item.cost_price
  }))

  const { error: itemErr } = await supabase
    .from('purchase_order_items')
    .insert(itemsToInsert)

  if (itemErr) throw new Error(itemErr.message)

  revalidatePath('/owner/purchase-orders')
  return po
}

export async function generateAutoPO() {
  const supabase = await createClient()

  // Workflow auto generate:
  // 1. Cari semua product yang reorder pointnya hit (stock <= min_stock)
  const { data: products } = await supabase.from('products').select('*')
  const reorderProducts = products?.filter(p => p.stock <= p.min_stock) || []
  
  if (reorderProducts.length === 0) {
    throw new Error('Semua stok aman, tidak ada barang yang perlu di reorder.')
  }

  // 2. Ambil supplier_products untuk cari supplier termurah tiap produk
  const { data: sps } = await supabase.from('supplier_products').select('*')
  
  // Kelompokkan pesanan by supplier_id
  const ordersBySupplier: Record<string, any[]> = {}

  for (const prod of reorderProducts) {
    const vendors = sps?.filter(sp => sp.product_id === prod.id) || []
    
    // Jika tidak ada supplier terhubung, kita abaikan saja untuk auto-PO
    if (vendors.length === 0) continue

    // Cari vendor termurah
    const cheapest = vendors.sort((a,b) => Number(a.cost_price) - Number(b.cost_price))[0]
    
    const targetQty = prod.min_stock * 3
    const orderQty = Math.max(1, targetQty - prod.stock)

    if (!ordersBySupplier[cheapest.supplier_id]) {
        ordersBySupplier[cheapest.supplier_id] = []
    }
    
    ordersBySupplier[cheapest.supplier_id].push({
       product_id: prod.id,
       qty: orderQty,
       cost_price: Number(cheapest.cost_price),
       product_name: prod.name
    })
  }

  const generatedPOs = []

  // 3. Create PO per supplier
  for (const supplier_id of Object.keys(ordersBySupplier)) {
     if (ordersBySupplier[supplier_id].length > 0) {
        const po = await createPurchaseOrder({
           supplier_id,
           notes: 'Auto-generated by System based on Reorder Points.',
           items: ordersBySupplier[supplier_id]
        })
        generatedPOs.push(po)
     }
  }

  if (generatedPOs.length === 0) {
      throw new Error('Reorder deteksi barang kurang, namun tidak ada vendor yang ditautkan ke produk tersebut. Harap tautkan produk ke vendor terlebih dahulu.')
  }

  revalidatePath('/owner/purchase-orders')
  return generatedPOs
}

export async function completePurchaseOrder(poId: string) {
    const supabase = await createClient()

    // Ambil full data po
    const { data: po } = await supabase.from('purchase_orders').select('*').eq('id', poId).single()
    if (!po) throw new Error('Data PO tidak ditemukan.')
    if (po.status !== 'PENDING') throw new Error('Hanya PO PENDING yang dapat diselesaikan.')

    // Ambil items
    const { data: items } = await supabase.from('purchase_order_items').select('*').eq('po_id', poId)
    if (!items || items.length === 0) throw new Error('PO tidak memiliki item.')

    // Eksekusi logic Create Stock Purchase (kulakan) per item
    // untuk merecord transaksi keluaran dana dan menambah stok
    for (const item of items) {
        await createStockPurchase({
            supplier_id: po.supplier_id,
            product_id: item.product_id,
            qty: item.qty,
            total_cost: item.qty * item.cost_price
        })
    }

    // Update status PO
    const { error } = await supabase
       .from('purchase_orders')
       .update({ 
           status: 'SELESAI', 
           completed_at: new Date().toISOString() 
        })
       .eq('id', poId)

    if (error) throw new Error(error.message)
    
    revalidatePath('/owner/purchase-orders')
    return true
}

export async function cancelPurchaseOrder(poId: string) {
    const supabase = await createClient()

    // Update status PO to DIBATALKAN
    const { error } = await supabase
       .from('purchase_orders')
       .update({ 
           status: 'DIBATALKAN'
        })
       .eq('id', poId)

    if (error) throw new Error(error.message)
    
    revalidatePath('/owner/purchase-orders')
    return true
}

export async function deletePurchaseOrder(poId: string) {
    const supabase = await createClient()

    // Hanya PO PENDING atau DIBATALKAN yang bisa dihapus
    const { data: po } = await supabase.from('purchase_orders').select('status').eq('id', poId).single()
    if (!po) throw new Error('PO tidak ditemukan.')
    if (po.status === 'SELESAI') throw new Error('PO yang sudah selesai tidak dapat dihapus.')

    // Hapus items dulu (cascade seharusnya sudah handle, tapi explicit lebih aman)
    await supabase.from('purchase_order_items').delete().eq('po_id', poId)
    
    const { error } = await supabase.from('purchase_orders').delete().eq('id', poId)
    if (error) throw new Error(error.message)

    revalidatePath('/owner/purchase-orders')
    return true
}

export async function updatePurchaseOrder(poId: string, data: { notes?: string; supplier_id?: string }) {
    const supabase = await createClient()

    const { data: po } = await supabase.from('purchase_orders').select('status').eq('id', poId).single()
    if (!po) throw new Error('PO tidak ditemukan.')
    if (po.status !== 'PENDING') throw new Error('Hanya PO berstatus PENDING yang dapat diedit.')

    const { error } = await supabase.from('purchase_orders').update(data).eq('id', poId)
    if (error) throw new Error(error.message)

    revalidatePath('/owner/purchase-orders')
    return true
}

